spring:
    application:
        name: AnnotationTest
    datasource:
        url: jdbc:mysql://localhost:3306/test
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
